from enum import IntEnum


class BindStatus(IntEnum):
    OK = 1
    TOKEN_INVALID = 2
    ACCOUNT_ABNORMAL = 3


CURSOR_MSG_TYPE = 3
CURSOR_NOTIFY_LINK = "/me"
NOTIFY_COOLDOWN_SECONDS = 24 * 3600
SYNC_FAIL_THRESHOLD = 3
# Celery beat runs sync_all_cursor_usage every 2 hours; allow one missed cycle.
SYNC_STALE_SECONDS = 150 * 60
ACCESS_TOKEN_REFRESH_THRESHOLD_SECONDS = 5 * 60

# 用量历史保留策略（可通过环境变量覆盖）
CURSOR_DAILY_USAGE_RETENTION_DAYS = 365
CURSOR_SYNC_LOG_RETENTION_DAYS = 365
CURSOR_CALENDAR_MONTH_RETENTION_MONTHS = 12
CURSOR_MONTHLY_CYCLE_RETENTION = 12
